# Generated by Django 4.2.11 on 2024-03-20 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='images',
            field=models.ImageField(null=True, upload_to='images/product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='adminpanel.product'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='imageUrl',
            field=models.ImageField(null=True, upload_to='images/shop'),
        ),
    ]
